INSERT INTO `setlist` ( `title`, `artist`, `style`) VALUES
( 'Pause', 'Compo', 'Apéro Concert'),
( 'Lettre à France', 'M. Polnareff', 'Apéro Concert'),
( 'Hymne à l\'amour', 'E. Piaf', 'Apéro Concert'),
( 'Let it be', 'Beatles', 'Apéro Concert'),
( 'Hallelujah', 'J. Buckey', 'Apéro Concert'),
( 'Your Song', 'E. John', 'Apéro Concert'),
( 'Lucie', 'P. Obispo', 'Apéro Concert'),
( 'Toi + moi', 'Grégoire', 'Apéro Concert'),
( 'Shape of my heart', 'Sting', 'Apéro Concert'),
( 'SOS', 'D. Balavoine', 'Apéro Concert'),
( 'Colorblind', 'Counting Crows', 'Apéro Concert'),
( 'J\'ai oublié de l\'oublier', 'E. Mitchell', 'Apéro Concert'),
( 'Kissing you', 'Dees\'re', 'Apéro Concert'),
( 'C\'est bon pour le moral', 'C. Créole', 'Tour du Monde - Créole'),
( 'Le douanier rousseau', 'C. Créole', 'Tour du Monde - Créole'),
( 'Ca fait rire les oiseaux', 'C. Créole', 'Tour du Monde - Créole'),
( 'Ai se tu e pego', 'M. Telo', 'Tour du Monde - Tube été'),
( 'Lambada', 'Kaoma', 'Tour du Monde - Tube été'),
( 'Samba de janeiro', 'Bellini', 'Tour du Monde - Tube été'),
( 'La Bamba', 'Los Lobos', 'Tour du Monde - Tube été'),
( 'No woman no cry', 'B. Marley', 'Tour du Monde - Reggae'),
( 'Reggae Night', 'J. Cliff', 'Tour du Monde - Reggae'),
( 'Ville de lumière', 'Gold', '80s, Disco, Funk - Gold'),
( 'Plus près des étoiles', 'Gold', '80s, Disco, Funk - Gold'),
( 'Capitaine abandonné', 'Gold', '80s, Disco, Funk - Gold'),
( 'Nuit de folie', 'Début de soirée', '80s, Disco, Funk - Medley 80'),
( 'Macumba', 'J.P Mader', '80s, Disco, Funk - Medley 80'),
( 'Le Jerk', 'T. Hazard', '80s, Disco, Funk - Medley 80'),
( 'Les démons de minuits', 'Image', '80s, Disco, Funk - Medley 80'),
( 'Gimme Gimme Gimme', 'ABBA', '80s, Disco, Funk - Disco'),
( 'Hot Stuff', 'D. Sommer', '80s, Disco, Funk - Disco'),
( 'Call Me', 'Blondie', '80s, Disco, Funk - Disco'),
( 'I Will Survive', 'G. Glaynor', '80s, Disco, Funk - Disco'),
( 'Magnolia forever', 'C. François', '80s, Disco, Funk - Cloclo'),
( 'Cette année là', 'C. François', '80s, Disco, Funk - Cloclo'),
( 'Staying alive', 'Beegees', '80s, Disco, Funk - Medley Funk'),
( 'Long train running', 'Dobbie Brothers', '80s, Disco, Funk - Medley Funk'),
( 'Le Freak', 'Chic', '80s, Disco, Funk - Medley Funk'),
( 'Je marche seul', 'J.J Goldman', 'Goldman & Cie'),
( 'Quand la musique est bonne', 'J.J Goldman', 'Goldman & Cie'),
( 'Il suffira d\'un signe', 'J.J Goldman', 'Goldman & Cie'),
( 'Encore un matin', 'J.J Goldman', 'Goldman & Cie'),
( 'Envole moi', 'J.J Goldman', 'Goldman & Cie'),
( 'J\'irai ou tu iras', 'JJ. Goldman / C. Dion', 'Goldman & Cie'),
( 'L\'aventurier', 'Indochine', '80s, Disco, Funk'),
( 'Sunlight des tropiques', 'G. Montagné', '80s, Disco, Funk - Montagné'),
( 'On va s\'aimer', 'G. Montagné', '80s, Disco, Funk - Montagné'),
( 'A Whiter Shade Of Pale', 'Procol Harum', 'Love & Slows'),
( 'Si (Zaz) : 113', 'Zaz', 'Love & Slows'),
( 'Knocking heaven\'s door : 110', 'Guns & Roses', 'Love & Slows'),
( 'La derniere danse : 111', 'Kyo', 'Love & Slows'),
( 'No woman no cry (copie dans reggae)', 'B. Marley', 'Love & Slows'),
( 'Stil got the blues', 'G. Moore', 'Love & Slows'),
( 'Still loving you : 120', 'Scorpion', 'Love & Slows'),
( 'Nothing else matter : 121', 'Metallica', 'Love & Slows'),
( 'I Will always love you : 122', 'W. Houston', 'Love & Slows'),
( 'Vivo per lei', 'A. Boccelli & H. Ségara', 'Love & Slows'),
( 'La bas', 'J.J. Goldman', 'Love & Slows'),
( 'Heros', 'M. Carey', 'Love & Slows'),
( 'Glory Box', 'Portishead', 'Love & Slows'),
( 'Shallow (A Star is Born) - à venir', 'B. Cooper / Lady Gaga', 'Love & Slows'),
( 'My Immortal', 'Evanescence', 'Rock - Slow'),
( 'Belles, belles, belles', 'C. François', 'Sixties - Twist'),
( 'Twist again', 'C. Checker', 'Sixties - Twist'),
( 'Johnny be good', 'C. Berry', 'Sixties - Rock\'n roll'),
( 'Blues suedes shoes', 'E. Presley', 'Sixties - Rock\'n roll'),
( 'The One That I Want', 'Grease', 'Sixties - Rock\'n roll'),
( 'Last night (impro)', '', 'Sixties - Madison'),
( 'Champs Elysée', 'J. Dassin', 'Sixties - Madison'),
( 'Wonderwall', 'Oasis', 'Pop Music'),
( 'A ma place', 'A. Bauer & Zazie', 'Pop Music'),
( 'Hotel California', 'Eagles', 'Pop Music'),
( 'Cendrillon', 'Téléphone', 'Rock - Téléphone'),
( 'I Love Rock\'n roll', 'J. Jett', 'Rock - Téléphone'),
( 'Bohemian Rhapsody', 'Queen', 'Rock - Queen'),
( 'We are the Champion', 'Queen', 'Rock - Queen'),
( 'Show must go on', 'Queen', 'Rock - Queen'),
( 'Rock you', 'Queen', 'Rock - Queen'),
( 'Eye of the tiger', 'Survivor', 'BO'),
( 'Ghostbuster', 'R. Parker Jr', 'BO'),
( 'The power of love', 'Frankie Goes to Hollywood', 'BO'),
( 'Bring me to life', 'Evanescence', 'BO'),
( 'Shallow', 'B. Cooper, L. Gaga', 'BO'),
( 'Starlight', 'Muse', 'Rock around the world'),
( 'Zombie', 'Cranberries', 'Rock around the world'),
( 'Seven nation', 'White stripes', 'Rock around the world'),
( 'Feeling good', 'Muse', 'Rock around the world'),
( 'Beat it', 'M. Jackson', 'Rock around the world'),
( 'Gotta get away', 'The Offspring', 'Rock around the world'),
( 'Ca c\'est vraiment toi', 'Téléphone', 'Rock around the world'),
( 'Highway to Hell', 'ACDC', 'Rock around the world'),
( 'Smoke on the water', 'Deep Purple', 'Rock around the world'),
( 'Hold the line', 'Toto', 'Rock around the world'),
( 'I was made for loving you', 'Kiss', 'Rock around the world'),
( 'Que je t\'aime', 'J. Halliday', 'Rock - Johnny'),
( 'Allumer le feu', 'J. Halliday', 'Rock - Johnny'),
( 'L\'envie', 'J. Halliday', 'Rock - Johnny'),
( 'Je ne suis pas un héros', 'D. Balavoine', 'Rock frenchies'),
( 'Mourir Demain', 'P. Obispo / N. StPier', 'Rock frenchies'),
( 'Sunday bloody Sunday', 'U2', 'Rock - U2'),
( 'Where the streets have no name', 'U2', 'Rock - U2'),
( 'New year\'s day', 'U2', 'Rock - U2'),
( 'The kids aren\'t alright', 'The Offspring', 'Rock - Punk'),
( 'Pretty fly (for a white guy)', 'The Offspring', 'Rock - Punk'),
( 'Un jour en France', 'Noir Désir', 'Rock - Noir Désir'),
( 'L\'homme pressé', 'Noir Désir', 'Rock - Noir Désir'),
( 'Emma', 'Matmatah', 'Rock - Matmatah'),
( 'Lambé', 'Matmatah', 'Rock - Matmatah'),
( 'C\'est toi que je t\'aime', 'Inconnus', 'Rock - Matmatah'),
( 'Marcia Baila', 'Rita mitsouko', 'Ambiance / Fête'),
( 'La salsa du démon', 'Le Splendide', 'Ambiance / Fête'),
( 'Tourner les serviettes', 'P. Sebastien', 'Ambiance / Fête - P Sébastien'),
( 'Les sardines', 'P. Sebastien', 'Ambiance / Fête - P Sébastien'),
( 'Les lacs du Connemara', 'M. Sardou', 'Ambiance / Fête - Danse Folk'),
( 'Rolling in the deep', 'Adèle', 'Ambiance / Fête - Adèle'),
( 'Someone like you', 'Adèle', 'Ambiance / Fête - Adèle'),
( 'Get lucky', 'Daft Punk', 'Actualté'),
( 'Everybody', 'M. Solveig', 'Actualté'),
( 'Locked out of heaven', 'B. Mars', 'Actualté'),
( 'I Gotta Feeling', 'D. Getta', 'Actualté'),
( 'Chandelier', 'Sia', 'Actualté'),
( 'Lose Yourself', 'Eminem', 'Rap');